  
version: "3.7"

services:

  flask:
    build: ./flask_app
    container_name: flask_app
    restart: always
    expose:
      - 900

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:1234"
